from tkinter import *
from tkinter import messagebox
root = Tk()
h,w = root.winfo_screenheight(), root.winfo_screenwidth()
root.geometry('%dx%d+0+0'%(w,h))
bus = PhotoImage(file = ".\\Bus_for_project.png")
Label(root, image = bus).grid(row = 0, column = 0, columnspan = 10, padx = w//3)
blank = Label(root, text = "                            " )
blank.grid(row = 1, column = 1)
title = Label(root, text = "Online Bus Booking System" , fg = 'red' , bg = 'lightblue', font = 'Arian 14 bold')
title.grid(row = 2, column = 0, columnspan = 10)
blank = Label(root, text = "                            " )
blank.grid(row = 3, column = 0)
blank = Label(root, text = "                            " )
blank.grid(row = 4, column = 0)
blank = Label(root, text = "                            " )
blank.grid(row = 5, column = 0)
title = Label(root, text = "Add Bus Running Details" , fg = 'green' , font = 'Arian 14 bold')
title.grid(row = 6, column = 0, columnspan = 10)
blank = Label(root, text = "                            " )
blank.grid(row = 7, column = 0)
blank = Label(root, text = "                            " )
blank.grid(row = 8, column = 0)
blank = Label(root, text = "                            " )
blank.grid(row = 9, column = 0)
route_text = Label(root, text = "Bus Id")
route_text.grid(row=10, column=0)
route_ent = Entry(root)
route_ent.grid(row=10, column=1)
station_text = Label(root, text = "Running Date")
station_text.grid(row=10, column=2)
station_ent = Entry(root)
station_ent.grid(row=10, column=3)
id_text = Label(root, text = "Seat Available")
id_text.grid(row=10, column=4)
id_ent = Entry(root)
id_ent.grid(row=10, column=5)
import sqlite3
with sqlite3.connect('database.db') as con:
    cur = con.cursor()
def add_busrun():
    a=route_ent.get()
    b=station_ent.get()
    c=id_ent.get()
    if(a==''or b==''or c==''):
        messagebox.showwarning("EMPTY DETAILS", "PLEASE ENTER ALL DETAILS")
    else:
        cur.execute('''insert into running_details(bus_id,running_date,seat_availaible) values(?,?,?)''',(a,b,c))
        con.commit()
        con.close()
        Label(root,text=" "+route_ent.get()+"  "+station_ent.get()+"  "+id_ent.get()+"  ").grid(row=11,column=4,columnspan=3)
        messagebox.showinfo("BUS RUN","RUNNING DETAILS ADDED SUCCESFULLY")
def del_busrun():
    a=route_ent.get()
    b=station_ent.get()
    c=id_ent.get()
    if(a==''or b==''or c==''):
        messagebox.showwarning("EMPTY DETAILS", "PLEASE ENTER ALL DETAILS")
    else:
        cur.execute('''delete from running_details where running_date=? and bus_id=?''',(b,a))
        con.commit()
        con.close()
        messagebox.showinfo("BUS RUN DELETED","RUNNING DETAILS DELETED SUCCESFULLY")
add_but = Button(root, text = "Add Run", bg ="lightgreen",command=add_busrun)
add_but.grid(row = 10, column = 6)
edit_but = Button(root, text = "Delete Run", bg = "lightgreen",command=del_busrun)
edit_but.grid(row = 10, column = 7)
blank = Label(root, text = "                            " )
blank.grid(row = 11, column = 0)
blank = Label(root, text = "                            " )
blank.grid(row = 12, column = 0)
blank = Label(root, text = "                            " )
blank.grid(row = 13, column = 0)
def home():
    root.destroy()
    import home_page
house = PhotoImage(file = ".\\home.png")
house_but = Button(root, image=house,command=home)
house_but.grid(row = 14, column = 6)
root.mainloop()