from tkinter import *
from tkinter import messagebox
root = Tk()
h,w = root.winfo_screenheight(), root.winfo_screenwidth()
root.geometry('%dx%d+0+0'%(w,h))
bus = PhotoImage(file = ".\\Bus_for_project.png")
Label(root, image = bus).grid(row = 0, column = 0, columnspan = 12, padx = w//3)
blank = Label(root, text = "                            " )
blank.grid(row = 1, column = 0)
title = Label(root, text = "Online Bus Booking System" , fg = 'red' , bg = 'lightblue', font = 'Arian 20 bold')
title.grid(row = 2, column = 0, columnspan = 12)
blank = Label(root, text = "                            " )
blank.grid(row = 3, column = 0)
blank = Label(root, text = "                            " )
blank.grid(row = 4, column = 0)
blank = Label(root, text = "                            " )
blank.grid(row = 5, column = 0)
add_text = Label(root, text = "Add Bus Operator Details",  fg = "green", font = 'Arian 20 bold')
add_text.grid(row = 6, column = 0, columnspan = 12)
blank = Label(root, text = "                            " )
blank.grid(row = 7, column = 0)
blank = Label(root, text = "                            " )
blank.grid(row = 8, column = 0)
blank = Label(root, text = "                            " )
blank.grid(row = 9, column = 0)
id_text = Label(root, text = "Operator id")
id_text.grid(row = 10, column = 0)
id_ent = Entry(root, width= 10)
id_ent.grid(row = 10, column =1)
op_id=id_ent.get()
name_text = Label(root, text = "Name")
name_text.grid(row = 10, column = 2)
name_ent = Entry(root)
name_ent.grid(row = 10, column =3)
name=name_ent.get()
address_text = Label(root, text = "Address")
address_text.grid(row = 10, column = 4)
address_ent = Entry(root)
address_ent.grid(row = 10, column =5)
address = address_ent.get()
phone_text = Label(root, text = "Mobile No.")
phone_text.grid(row = 10, column = 6)
phone_ent = Entry(root)
phone_ent.grid(row = 10, column =7)
phone = phone_ent.get()
email_text = Label(root, text = "Email")
email_text.grid(row = 10, column = 8)
email_ent = Entry(root)
email_ent.grid(row = 10, column =9)
email = email_ent.get()
import sqlite3
with sqlite3.connect('database.db') as con:
    cur = con.cursor()
def add_bus_operator():
    op_id=id_ent.get()
    name=name_ent.get()
    address = address_ent.get()
    phone = phone_ent.get()
    email = email_ent.get()
    if(op_id==''or name==''or address==''or phone==''or email==''):
        messagebox.showwarning("EMPTY DETAILS", "PLEASE ENTER ALL DETAILS")
    else:   
        cur.execute('''insert into bus_operator(op_id,name,address,phone,email) values(?,?,?,?,?)''',(op_id,name,address,phone,email))
        con.commit()
        messagebox.showinfo('OPERATOR','OPERATOR RECORD ADDED SUCCESFULLY')
        Label(root,text=" "+id_ent.get()+"  "+name_ent.get()+"  "+address_ent.get()+"  "+phone_ent.get()+"  "+email_ent.get()).grid(row=11,column=4,columnspan=3)
def edit_bus_operator():
    op_id=id_ent.get()
    name=name_ent.get()
    address = address_ent.get()
    phone = phone_ent.get()
    email = email_ent.get()
    if(op_id==''or name==''or address==''or phone==''or email==''):
        
        messagebox.showwarning("EMPTY DETAILS", "PLEASE ENTER ALL DETAILS")
    else:   
        cur.execute('''update bus_operator set name=?,address=?,phone=?,email=? where op_id=?''',(name,address,phone,email,op_id))
        con.commit()
        messagebox.showinfo("OPERATOR RECORD UPTADE", "OPERATOR RECORD UPDATED SUCCESSFULLY")
add_but = Button(root, text = "Add", bg= "lightgreen",command=add_bus_operator)
add_but.grid(row =10, column = 10)
edit_but = Button(root, text = "Edit", bg = "lightgreen", command = edit_bus_operator)
edit_but.grid(row =10, column = 11)
blank = Label(root, text = "                            " )
blank.grid(row = 11, column = 0)
blank = Label(root, text = "                            " )
blank.grid(row = 12, column = 0)
def home():
    root.destroy()
    import home_page
houses = PhotoImage(file = ".\\home.png")
Button(root, image = houses,command=home).grid(row = 13, column = 8)
root.mainloop()