import sqlite3
con = sqlite3.Connection('database.db')
cur = con.cursor()
# cur.execute("create table passenger(passenger_id integer NOT NULL primary key autoincrement,name varchar(50),gender varchar(20),no_of_seats int,mob_no int,age int,booking_date date,travelling_date date,bus_id int,foreign key(bus_id) references bus(bus_id)) ")
# cur.execute("create table bus(bus_id int,bus_type varchar(30),capacity int ,fare int,op_id int, route_id int,primary key(bus_id),foreign key (op_id) references bus_operator(op_id),foreign key (route_id) references route(route_id))")
# cur.execute("create table route(route_id int ,station_name varchar(30),station_id int,primary key(route_id,station_id))")
# cur.execute("create table running_details(bus_id int,running_date date,seat_availaible int,primary key(bus_id,running_date))")
# cur.execute("create table bus_operator(op_id int ,name varchar(30),address varchar(30),phone int,email varchar(3),primary key(op_id))")
# cur.execute("create table route(route_id int ,station_name varchar(30),station_id int)")
# cur.execute("create table passenger(name varchar(50),gender varchar(20),no_of_seats int,mob_no int,age int ,primary key(mob_no))")
# cur.execute("drop table ticket")
# cur.execute("delete from running_details where bus_id=22 and running_date=23/01/2022")
cur.execute('''update bus set availaible_seats=25 where bus_id=4''' )
con.commit()
con.close()
